#:schema node_modules/wrangler/config-schema.json
name = "web-scrapper"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat_v2"]

browser = { binding = "CRAWLER_BROWSER" }

[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[kv_namespaces]]
binding = "CRAWLER_PAGE_CACHE"
id = "a18ff6ce1fb94d9093721eb3c496d2fa"
preview_id = "2f496917fa6248bdbbc3ca5021ca6d2d"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes